import { getNode, resolvePath, formatPath } from './fs';
import { getProject } from './content';
import { renderMarkdown } from './markdown';

export interface ShellState {
  cwd: string[];
  // Set by a handler (e.g. `open`) to request navigating to an external
  // URL; Terminal.tsx opens it in a new tab after the command runs.
  pendingLink?: string;
  // Set by a handler (e.g. `gui`) to request an in-app route change;
  // Terminal.tsx calls react-router's navigate() after the command runs.
  pendingNavigate?: string;
}

export type CommandHandler = (args: string[], state: ShellState) => string | Promise<string>;

const CONTACT_URL = 'https://github.com/ronniechong/ronniechong.github.io/issues/new';

function ls(args: string[], state: ShellState): string {
  const target = args[0] ? resolvePath(state.cwd, args[0]) : state.cwd;
  const node = getNode(target);
  if (!node) return `ls: no such file or directory: ${args[0] ?? formatPath(target)}`;
  if (node.type === 'file') return target[target.length - 1] ?? '';
  // Not alphabetized — DirNode.children already reflects the intended
  // display order (pages alphabetical, projects newest-first; see
  // content.ts), and toDir() builds children by insertion order to match.
  const names = Object.keys(node.children);
  return names.length ? names.join('\n') : '(empty)';
}

function cd(args: string[], state: ShellState): string {
  const target = args[0] ? resolvePath(state.cwd, args[0]) : [];
  const node = getNode(target);
  if (!node) return `cd: no such directory: ${args[0]}`;
  if (node.type !== 'dir') return `cd: not a directory: ${args[0]}`;
  state.cwd = target;
  return '';
}

function cat(args: string[], state: ShellState): string {
  const name = args[0];
  if (!name) return "cat: missing file name, e.g. 'cat about.md'";
  const target = resolvePath(state.cwd, name);
  const node = getNode(target);
  if (!node) return `cat: no such file: ${name}`;
  if (node.type !== 'file') return `cat: is a directory: ${name}`;
  return renderMarkdown(node.entry.body);
}

function open(args: string[], state: ShellState): string {
  const slug = args[0];
  if (!slug) return "open: missing project name, e.g. 'open generative-art'";
  const project = getProject(slug);
  if (!project) return `open: no such project: ${slug}`;
  const { title, link } = project.frontmatter;
  const parts = [`# ${title ?? slug}`, project.body];
  if (link) {
    parts.push(link);
    state.pendingLink = link;
  }
  return renderMarkdown(parts.join('\n\n'));
}

function gui(_args: string[], state: ShellState): string {
  state.pendingNavigate = '/app';
  return '';
}

interface LiveProject {
  repo: string;
  label: string;
  defaultBranch: string;
  lastCommitDate: string;
  lastCommitMessage: string;
  commitCount: number;
  openIssueCount: number;
}

interface LiveData {
  generatedAt: string;
  projects: LiveProject[];
}

// Coarse "time ago" — this is a portfolio's commit-freshness indicator, not
// a precise calendar, so month/year buckets use flat 30/365-day divisors.
function formatAge(dateStr: string): string {
  const minutes = Math.floor((Date.now() - new Date(dateStr).getTime()) / 60000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.floor(hours / 24);
  if (days < 30) return `${days}d ago`;
  const months = Math.floor(days / 30);
  if (months < 12) return `${months}mo ago`;
  return `${Math.floor(days / 365)}y ago`;
}

async function stats(): Promise<string> {
  let data: LiveData;
  try {
    const res = await fetch('/data/live.json');
    if (!res.ok) throw new Error(String(res.status));
    data = await res.json();
  } catch {
    return "stats: live data isn't available right now (this only exists on the deployed site, generated by CI on every push). Try again after the next deploy.";
  }
  const lines = data.projects.map(
    (p) =>
      `${p.label} (${p.repo})\n  branch ${p.defaultBranch} · ${formatAge(p.lastCommitDate)} · "${p.lastCommitMessage}"\n  ${p.commitCount} commits · ${p.openIssueCount} open issues`
  );
  return [`Live stats as of ${formatAge(data.generatedAt)}:`, '', ...lines].join('\n');
}

function whoami(): string {
  return "I'm just another tech perp on the interweb who solves 90% of life's problems by turning it off and back on again. Type 'cat /pages/about.md' for more.";
}

function contact(): string {
  return `Open an issue to get in touch: ${CONTACT_URL}`;
}

// Clears the visible screen and scrollback, then homes the cursor.
function clear(): string {
  return '\x1b[2J\x1b[3J\x1b[H';
}

const descriptions: Record<string, string> = {
  help: 'list available commands',
  whoami: 'short bio',
  ls: 'list current directory, or a given path',
  cd: "change directory, e.g. 'cd projects'",
  cat: "print a file, e.g. 'cat about.md'",
  open: "open a project, e.g. 'open generative-art' (opens its link in a new tab)",
  clear: 'clear the screen',
  contact: 'how to reach me',
  gui: "if you're commands-phobic, open the clickable version of this site",
  stats: 'live commit/issue stats for each project, pulled from GitHub',
};

function help(): string {
  return Object.entries(descriptions)
    .map(([name, desc]) => `${name.padEnd(8)} ${desc}`)
    .join('\n');
}

export const commands: Record<string, CommandHandler> = {
  help,
  whoami,
  ls,
  cd,
  cat,
  open,
  clear,
  contact,
  gui,
  stats,
};
